# docker-compose.yml file
version: '3'

services:
  # The load balancer
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "9000:80"

  # The web server1
  server1:
    image: nginx:1.16.0-alpine
    volumes:
      - ./server1:/usr/share/nginx/html

  # The web server2
  server2:
    image: nginx:1.16.0-alpine
    volumes:
      - ./server2:/usr/share/nginx/html
